name: MattAnderson
favicon: null
layout_spectrum: 0.5916042651515454
typography_spectrum: 0.5914274484384805
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#565656'
    - '#9f9f9f'
    - '#fbfcfc'
    - '#d7d7d7'
  brandStrength: 0.38251339131966233
  lightness: 0.769772638566792
  saturation: 0.8804097992833704
  rhythmicContrast: 0.8528174357488751
purpose: []
